### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 3.79 GiB total capacity; 654.97 MiB already allocated; 6.00 MiB free; 666.00 MiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by EllisHui** [MVIG-SJTU/AlphAction#58]
Dear friend:
Hello,Thanks for your amazing project!
when I run this command 
" python demo.py  --video-path /home/charles/code/AlphAction/config_files/run1.mp4 --output-path /home/charles/code/AlphAction/config_files/result1.mp4 --cfg-path /home/charles/code/AlphAction/config_files/resnet101_8x8f_denseserial.yaml  --weight-path /home/charles/code/AlphAction/config_files/common_15cat_res101.pth --common-cate"
the results are like below
"RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 3.79 GiB total capacity; 654.97 MiB already allocated; 6.00 MiB free; 666.00 MiB reserved in total by PyTorch)"
if you can give me some improvement advice ,i will be grateful

**Comment by EllisHui** [comment]
I have solved it.
Because the pytorch can't be higher than the 16

**Comment by EllisHui** [comment]
I have solved it.
Because the pytorch can't be higher than the 16

**Comment by EllisHui** [comment]
I have solved it.
Because the pytorch can't be higher than the 16
